import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Drawer from "./components/Drawer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-blue-100 via-white to-blue-200`}
      >
        <div className="flex flex-row min-h-screen">
          <Drawer />
          <main className="flex-1 flex flex-col pt-4 transition-all duration-300">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
